server:
  port: 8084
spring:
  data:
    mongodb:
      host: 0.0.0.0
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: mistergold_database